### ISSUE TITLE
Action can't set env vars anymore; fails unless you give it sudo

### ISSUE THREAD

**Issue by squillace** [getporter/gh-action#14]
Currently, the new prohibition against GH actions setting env vars and paths is blocking the action, resulting in this error:

```
Error: Unable to process command '::add-path::/home/runner/.porter' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

>A moderate security vulnerability has been identified in the GitHub Actions runner that can allow environment variable and path injection in workflows that log untrusted data to STDOUT. This can result in environment variables being introduced or modified without the intention of the workflow author.
>To allow us to address this issue and maintain the ability for you to dynamically set environment variables we have introduced a new set of files to manage environment and path updates in workflows.

We'll need to update the action to work properly.

**Comment by vdice** [comment]
@squillace please try again when/if convenient with the latest [v0.1.3](https://github.com/getporter/gh-action/releases/tag/v0.1.3) release.

**Comment by vdice** [comment]
I'm having success with the latest release (using in https://github.com/vdice/porter-bundles).  Closing, but feel free to re-open if issue(s) remain!
